version: '3.2'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2
    command: >
        /usr/local/bin/etcd
        -name etcd0
        -advertise-client-urls https://localhost:2379
        -listen-client-urls https://0.0.0.0:2379
        -initial-advertise-peer-urls http://0.0.0.0:2380
        -listen-peer-urls http://0.0.0.0:2380
        -initial-cluster-token etcd-cluster-1
        -initial-cluster etcd0=http://0.0.0.0:2380
        -initial-cluster-state new
        -enable-v2=false
        -auto-tls=true
    ports:
      - "2379:2379"
  proxy:
    image: shopify/toxiproxy:latest
    ports:
      - "22379:22379"
      - "8474:8474"
